//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_System.Business.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Registration_System.Business.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Created.
        /// </summary>
        internal static string DepartmentCreated {
            get {
                return ResourceManager.GetString("DepartmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Deleted.
        /// </summary>
        internal static string DepartmentDeleted {
            get {
                return ResourceManager.GetString("DepartmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is Not found.
        /// </summary>
        internal static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments List.
        /// </summary>
        internal static string DepartmentsList {
            get {
                return ResourceManager.GetString("DepartmentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Updated.
        /// </summary>
        internal static string DepartmentUpdated {
            get {
                return ResourceManager.GetString("DepartmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Created.
        /// </summary>
        internal static string EmployeeCreated {
            get {
                return ResourceManager.GetString("EmployeeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Deleted.
        /// </summary>
        internal static string EmployeeDeleted {
            get {
                return ResourceManager.GetString("EmployeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee is not found.
        /// </summary>
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees List.
        /// </summary>
        internal static string EmployeesList {
            get {
                return ResourceManager.GetString("EmployeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Updated.
        /// </summary>
        internal static string EmployeeUpdated {
            get {
                return ResourceManager.GetString("EmployeeUpdated", resourceCulture);
            }
        }
    }
}
